//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidgetWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int CartID { get; set; }
        public string UserName { get; set; }
        public bool IsFulfilled { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}
