//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidgetWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductReviews = new HashSet<ProductReview>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public int OrderMaximumQuantity { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string ImageSmall { get; set; }
        public string ImageLarge { get; set; }
        public decimal PriceModifier { get; set; }
    
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
    }
}
